### ISSUE TITLE
compilation failure from unused result warning

### ISSUE THREAD

**Issue by carns** [UO-OACISS/apex#161]
I'm trying to build the apex 2.4.1 spack package on Ubuntu 21.10 (gcc 11.2) and it fails with the following error:

```
  >> 300    /tmp/carns/spack-stage/spack-stage-apex-2.4.1-42sh5qjqx5m5kz5eowmvd
            6twzevxdk7b/spack-src/src/apex/proc_read.h:184:11: error: ignoring 
            return value of 'int fscanf(FILE*, const char*, ...)' declared with
             attribute 'warn_unused_result' [-Werror=unused-result]
     301      184 |     fscanf(fff,"%lld",&tmplong);
     302          |     ~~~~~~^~~~~~~~~~~~~~~~~~~~~
     303    /tmp/carns/spack-stage/spack-stage-apex-2.4.1-42sh5qjqx5m5kz5eowmvd
            6twzevxdk7b/spack-src/src/apex/proc_read.h: In function 'long long 
            int apex::read_dram()':
  >> 304    /tmp/carns/spack-stage/spack-stage-apex-2.4.1-42sh5qjqx5m5kz5eowmvd
            6twzevxdk7b/spack-src/src/apex/proc_read.h:201:11: error: ignoring 
            return value of 'int fscanf(FILE*, const char*, ...)' declared with
             attribute 'warn_unused_result' [-Werror=unused-result]
     305      201 |     fscanf(fff,"%lld",&tmplong);
     306          |     ~~~~~~^~~~~~~~~~~~~~~~~~~~~
```
I didn't explicitly ask that warnings be treated as errors.  Maybe the spack package or the apex build system is doing that, and gcc 11.2 is being more picky than expected?

**Comment by carns** [comment]
Ah, this may be resolved already?  I noticed that the line setting `-Werror` in cmake is commented out in the `develop` branch and tried building `apex@develop` in Spack.  That one installs fine.

**Comment by khuck** [comment]
Yeah, that's something I use in development that doesn't travel well, with many compilers.  It's since been commented out.  I recommend the develop branch anyway, there have been many changes to the code since 2.4.1, and I plan a release soon (once I nail down some more HIP/ROCm support to be robust)
