### ISSUE TITLE
APEX relies on zlib without checking if it's available

### ISSUE THREAD

**Issue by hkaiser** [UO-OACISS/apex#163]
See here for a build failure caused by relying on `#include <zlib.h>` without it being available: https://github.com/STEllAR-GROUP/hpx/runs/4838798276?check_suite_focus=true.

**Comment by khuck** [comment]
HPX / APEX _does_ check if zlib is available.  See https://github.com/UO-OACISS/apex/blob/develop/cmake/Modules/APEX_SetupZlib.cmake for the check, and `gzstream.hpp` should only get included if APEX_HAVE_ZLIB is set (https://github.com/UO-OACISS/apex/blob/b09eb7d94c9e329ce74aff29375ee9b7a384561b/src/apex/trace_event_listener.hpp#L15-L17).  Does the cmake `find_package(ZLIB)` step only check for the library, and not the development headers?
