### ISSUE TITLE
Building project_otf2 fails

### ISSUE THREAD

**Issue by akash-isu** [UO-OACISS/apex#165]
I'm trying to build APEX. I keep getting the following build error. The error originates from this file "_project_otf2-download-Release.cmake_". I've narrowed it down to this statement "`set(command "/usr/bin/cmake;-Dmake=${make};-Dconfig=${config};-P;/home/akashdutta/Documents/git_repos/apex-2.3.1/build/otf2-2.0/src/project_otf2-stamp/project_otf2-download-Release-impl.cmake`")".
I'm also attaching the log files. It seems it can't download otf2 from the mentioned URL.
[project_otf2-download-err.log](https://github.com/UO-OACISS/apex/files/8457465/project_otf2-download-err.log)
[project_otf2-download-out.log](https://github.com/UO-OACISS/apex/files/8457466/project_otf2-download-out.log)

```
[  1%] Performing update step for 'project_ompt'
Current branch master is up to date.
[  1%] Performing configure step for 'project_ompt'
-- project_ompt configure command succeeded.  See also /home/akashdutta/Documents/git_repos/apex-2.3.1/build/LLVM-ompt-5.0/src/project_ompt-stamp/project_ompt-configure-*.log
[  2%] Performing build step for 'project_ompt'
-- project_ompt build command succeeded.  See also /home/akashdutta/Documents/git_repos/apex-2.3.1/build/LLVM-ompt-5.0/src/project_ompt-stamp/project_ompt-build-*.log
[  3%] Performing install step for 'project_ompt'
-- project_ompt install command succeeded.  See also /home/akashdutta/Documents/git_repos/apex-2.3.1/build/LLVM-ompt-5.0/src/project_ompt-stamp/project_ompt-install-*.log
[  3%] Completed 'project_ompt'
[  3%] Built target project_ompt
[  6%] Built target project_activeharmony
[  6%] Performing download step (download, verify and extract) for 'project_otf2'
CMake Error at project_otf2-stamp/project_otf2-download-Release.cmake:49 (message):
  Command bal failed: 1

   '/usr/bin/cmake' '-Dmake=' '-Dconfig=' '-P' '/home/akashdutta/Documents/git_repos/apex-2.3.1/build/otf2-2.0/src/project_otf2-stamp/project_otf2-download-Release-impl.cmake'

  See also

    /home/akashdutta/Documents/git_repos/apex-2.3.1/build/otf2-2.0/src/project_otf2-stamp/project_otf2-download-*.log


make[2]: *** [CMakeFiles/project_otf2.dir/build.make:91: otf2-2.0/src/project_otf2-stamp/project_otf2-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:1210: CMakeFiles/project_otf2.dir/all] Error 2
make: *** [Makefile:141: all] Error 2

```

**Comment by khuck** [comment]
Sorry you are having problems... I just tried to download http://perftools.pages.jsc.fz-juelich.de/cicd/otf2/tags/otf2-2.3/otf2-2.3.tar.gz and it worked fine.  Maybe there was a problem with the server when you were trying to build?

**Comment by akash-isu** [comment]
I checked the log files. When I try to build it's trying to download from [http://www.vi-hps.org/upload/packages/otf2/otf2-2.0.tar.gz](url). Should I try and replace this with the juelich.de URL?

**Comment by akash-isu** [comment]
I was using the instructions here: [http://uo-oaciss.github.io/apex/install/](url). I downloaded the tar file and followed the steps. I'll try the same using the develop branch.

**Comment by akash-isu** [comment]
I was able to get it to work. I'm really new to this framework.
Is there a way tune OpenMP threads and scheduling policies if I don't Cmake and make it during installation?
Imagine I have a simple external OpenMP C file and I know how to compile and execute it. What steps should I follow so that APEX can tune it?

**Comment by khuck** [comment]
You should check out the instructions here: https://github.com/UO-OACISS/apex/wiki/Using-APEX-with-OpenMP#step-4-run-the-example for how to configure your program to be auto-tuned.

You will have to build APEX in order to use `apex_exec`, which is a shell script that will preload the APEX measurement libraries before running your program.  To use `apex_exec` with your OpenMP program, you would run it like:

```
apex_exec --apex:ompt <any other apex arguments> my_program <arguments> 
```
